<?php

declare(strict_types=1);

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

/**
 * Facebook Login for the Social Planner.
 *
 * The original connect flow asked the user to paste a Page Access Token they
 * had generated by hand in the Graph API Explorer. Two things were wrong with
 * that: the Explorer hands out a SHORT-LIVED token by default, so the
 * connection quietly died an hour or two later and every scheduled post after
 * that landed in `failed` with a Graph error nobody was watching; and a
 * long-lived page credential travelled through a browser form, a clipboard and
 * anything in between.
 *
 * OAuth fixes both: Meta hands the token straight to this server, and a page
 * token derived from a long-lived user token does not expire.
 *
 * social_oauth_states is the CSRF + correlation record for one connect attempt.
 * It exists because the callback arrives as a plain browser redirect and so
 * carries no Authorization header — `state` is the only thing tying Meta's
 * response back to the user who started the flow. Rows are single-use and
 * short-lived.
 */
class AddSocialOauth extends Migration
{
    public function up(): void
    {
        // --- social_accounts: expiry + reauth tracking ---------------------
        $this->forge->addColumn('social_accounts', [
            // NULL = never expires (the normal case for a page token derived
            // from a long-lived user token). A value here is a deadline we can
            // warn about before it bites.
            'token_expires_at' => [
                'type' => 'DATETIME', 'null' => true, 'after' => 'access_token_enc',
            ],
            // Who connected it, for the audit trail in a shared team account.
            'connected_by' => [
                'type' => 'INT', 'constraint' => 11, 'unsigned' => true,
                'null' => true, 'after' => 'token_expires_at',
            ],
            // How the credential was obtained. 'manual' rows are the legacy
            // hand-pasted tokens: the ones most likely to expire silently.
            'connect_method' => [
                'type' => 'ENUM', 'constraint' => ['oauth', 'manual'],
                'default' => 'manual', 'after' => 'connected_by',
            ],
            // Last Graph failure, so the UI can explain a dead connection
            // instead of just showing posts failing one by one.
            'last_error' => [
                'type' => 'TEXT', 'null' => true, 'after' => 'connect_method',
            ],
        ]);

        // status gains 'reauth_required' — set when Graph rejects the token, so
        // the page can prompt for a reconnect rather than failing in silence.
        $this->db->query(
            "ALTER TABLE {$this->db->DBPrefix}social_accounts
             MODIFY COLUMN status ENUM('active','error','reauth_required') NOT NULL DEFAULT 'active'"
        );

        // --- social_oauth_states ------------------------------------------
        $this->forge->addField([
            'id'        => ['type' => 'INT', 'constraint' => 11, 'unsigned' => true, 'auto_increment' => true],
            'tenant_id' => ['type' => 'INT', 'constraint' => 11, 'unsigned' => true],
            'user_id'   => ['type' => 'INT', 'constraint' => 11, 'unsigned' => true],
            // Random 64-char opaque value echoed by Meta on the callback.
            'state'     => ['type' => 'VARCHAR', 'constraint' => 64],
            // Long-lived USER token, encrypted. Held only between the callback
            // and the page choice, then wiped — we keep one user token rather
            // than a page token per page the user administers.
            'user_token_enc' => ['type' => 'TEXT', 'null' => true],
            // Display-only page list for the picker: id + name, never tokens.
            'pages_json'     => ['type' => 'TEXT', 'null' => true],
            'status'    => [
                'type'       => 'ENUM',
                'constraint' => ['pending', 'ready', 'consumed', 'failed'],
                'default'    => 'pending',
            ],
            'error'      => ['type' => 'TEXT', 'null' => true],
            'expires_at' => ['type' => 'DATETIME'],
            'created_at' => ['type' => 'DATETIME', 'null' => true],
            'updated_at' => ['type' => 'DATETIME', 'null' => true],
            'deleted_at' => ['type' => 'DATETIME', 'null' => true],
        ]);
        $this->forge->addKey('id', true);
        $this->forge->addUniqueKey('state');
        $this->forge->addKey(['tenant_id', 'status']);
        $this->forge->addForeignKey('tenant_id', 'tenants', 'id', 'CASCADE', 'CASCADE');
        $this->forge->createTable('social_oauth_states');
    }

    public function down(): void
    {
        $this->forge->dropTable('social_oauth_states', true);

        $this->db->query(
            "ALTER TABLE {$this->db->DBPrefix}social_accounts
             MODIFY COLUMN status ENUM('active','error') NOT NULL DEFAULT 'active'"
        );
        $this->forge->dropColumn('social_accounts', [
            'token_expires_at', 'connected_by', 'connect_method', 'last_error',
        ]);
    }
}
