import { api, openPdf as openFile, openPdf, downloadFile } from './client'

// Money is integer paise everywhere in the API; these helpers convert at the UI edge only.
export const inr = (paise, compact = false) => {
  const n = Number(paise || 0) / 100
  if (compact && Math.abs(n) >= 100000) return '₹' + (n / 100000).toFixed(n >= 1000000 ? 1 : 2).replace(/\.?0+$/, '') + 'L'
  return '₹' + n.toLocaleString('en-IN', { maximumFractionDigits: 0 })
}
export const toPaise = (rupees) => Math.round(Number(rupees || 0) * 100)

const unwrap = (r) => r.data

export const travel = {
  // master data
  list:    (res, q = '')      => api.get(`/travel/${res}${q ? `?${q}` : ''}`).then(unwrap),
  create:  (res, body)        => api.post(`/travel/${res}`, body).then(unwrap),
  update:  (res, id, body)    => api.put(`/travel/${res}/${id}`, body).then(unwrap),
  remove:  (res, id)          => api.delete(`/travel/${res}/${id}`),
  adsReport: (from, to)       => api.get(`/travel/reports/ads?from=${from}&to=${to}`).then(unwrap),

  // home dashboard (managers may pass a user id to focus on one person)
  home:        (userId)       => api.get(`/home${userId ? `?user=${userId}` : ''}`).then(unwrap),
  // trips
  trips:       (q = '')       => api.get(`/trips${q ? `?${q}` : ''}`).then(unwrap),
  trip:        (id)           => api.get(`/trips/${id}`).then(unwrap),
  createTrip:  (body)         => api.post('/trips', body).then(unwrap),
  updateTrip:  (id, body)     => api.put(`/trips/${id}`, body).then(unwrap),
  setTripStatus: (id, status, lost_reason) => api.post(`/trips/${id}/status`, { status, lost_reason }).then(unwrap),
  aiParse:     (text)         => api.post('/trips/ai-parse', { text }).then(unwrap),
  aiItinerary: (id)           => api.post(`/trips/${id}/ai-itinerary`).then(unwrap),

  // itineraries
  itineraries:    (q = '')    => api.get(`/itineraries${q ? `?${q}` : ''}`).then(unwrap),
  itinerary:      (id)        => api.get(`/itineraries/${id}`).then(unwrap),
  createItinerary:(body)      => api.post('/itineraries', body).then(unwrap),
  updateItinerary:(id, body)  => api.put(`/itineraries/${id}`, body).then(unwrap),
  addDay:         (id, body)  => api.post(`/itineraries/${id}/days`, body).then(unwrap),
  addItem:        (id, body)  => api.post(`/itineraries/${id}/items`, body).then(unwrap),
  deleteItem:     (id, itemId)=> api.delete(`/itineraries/${id}/items/${itemId}`).then(unwrap),
  newVersion:     (id)        => api.post(`/itineraries/${id}/version`).then(unwrap),
  share:          (id)        => api.post(`/itineraries/${id}/share`).then(unwrap),

  // bookings
  bookings:     (q = '')      => api.get(`/bookings${q ? `?${q}` : ''}`).then(unwrap),
  booking:      (id)          => api.get(`/bookings/${id}`).then(unwrap),
  bookingsDashboard: ()       => api.get('/bookings/dashboard').then(unwrap),
  createBooking:(body)        => api.post('/bookings', body).then(unwrap),
  markPaid:     (paymentId, body) => api.post(`/bookings/payments/${paymentId}/paid`, body).then(unwrap),
  updateService:(id, body)    => api.patch(`/bookings/services/${id}`, body).then(unwrap),
  addTraveler:  (id, body)    => api.post(`/bookings/${id}/travelers`, body).then(unwrap),
  paymentLink:  (paymentId)   => api.post(`/bookings/payments/${paymentId}/link`).then(unwrap),
  remindNow:    (paymentId)   => api.post(`/bookings/payments/${paymentId}/remind`).then(unwrap),
  reminders:    (paymentId)   => api.get(`/bookings/payments/${paymentId}/reminders`).then(unwrap),
  dunning:      ()            => api.get('/dunning/settings').then(unwrap),
  saveDunning:  (body)        => api.put('/dunning/settings', body).then(unwrap),
  setupDunningTemplates: ()   => api.post('/dunning/setup-templates').then(unwrap),
  adPlatforms:      ()      => api.get('/ad-platforms').then(unwrap),
  saveMeta:         (body)  => api.put('/ad-platforms/meta', body).then(unwrap),
  testMeta:         ()      => api.post('/ad-platforms/meta/test').then(unwrap),
  googleStart:      ()      => api.post('/ad-platforms/google/start').then(unwrap),
  googleCustomers:  ()      => api.get('/ad-platforms/google/customers').then(unwrap),
  googleAccount:    (body)  => api.put('/ad-platforms/google/account', body).then(unwrap),
  googleActions:    ()      => api.get('/ad-platforms/google/actions').then(unwrap),
  googleMapping:    (body)  => api.put('/ad-platforms/google/mapping', body).then(unwrap),
  disconnectAd:     (p)     => api.delete(`/ad-platforms/${p}`).then(unwrap),
  deliveries:       ()      => api.get('/ad-platforms/deliveries').then(unwrap),
  retryDelivery:    (id)    => api.post(`/ad-platforms/deliveries/${id}/retry`).then(unwrap),
  automations:        ()     => api.get('/travel-automations').then(unwrap),
  installAutomations: (keys) => api.post('/travel-automations/install', keys ? { keys } : {}).then(unwrap),
  // campaign management
  fxRates:         ()           => api.get('/fx').then(unwrap),
  addFx:           (b)          => api.post('/fx', b).then(unwrap),
  setFx:           (c, b)       => api.put(`/fx/${c}`, b).then(unwrap),
  fxAuto:          (c)          => api.post(`/fx/${c}/auto`).then(unwrap),
  refreshFx:       ()           => api.post('/fx/refresh').then(unwrap),
  removeFx:        (c)          => api.delete(`/fx/${c}`).then(unwrap),
  fxHistory:       (c)          => api.get(`/fx/${c}/history`).then(unwrap),
  relockFx:        (itId)       => api.post(`/itineraries/${itId}/relock-fx`).then(unwrap),
  ratePreview:     (b, file)    => { if (!file) return api.post('/travel/rate-import/preview', b).then(unwrap); const f = new FormData(); Object.entries(b).forEach(([k, v]) => v != null && v !== '' && f.append(k, v)); f.append('file', file); return api.post('/travel/rate-import/preview', f).then(unwrap) },
  rateCommit:      (id, b)      => api.post(`/travel/rate-import/${id}/commit`, b).then(unwrap),
  adAssets:        ()           => api.get('/ad-campaigns/assets').then(unwrap),
  uploadAdAsset:   (file)       => { const f = new FormData(); f.append('file', file); return api.post('/ad-campaigns/assets', f).then(unwrap) },
  deleteAdAsset:   (id)         => api.delete(`/ad-campaigns/assets/${id}`).then(unwrap),
  adAudiences:     ()           => api.get('/ad-campaigns/audiences').then(unwrap),
  createAudience:  (b)          => api.post('/ad-campaigns/audiences', b).then(unwrap),
  createLookalike: (b)          => api.post('/ad-campaigns/audiences/lookalike', b).then(unwrap),
  refreshAudience: (id)         => api.post(`/ad-campaigns/audiences/${id}/refresh`).then(unwrap),
  audienceEstimate: (id)        => api.get(`/ad-campaigns/audiences/${id}/estimate`).then(unwrap),
  deleteAudience:  (id)         => api.delete(`/ad-campaigns/audiences/${id}`).then(unwrap),
  adCampaigns:     (days = 30)  => api.get(`/ad-campaigns?days=${days}`).then(unwrap),
  adConnection:    ()           => api.get('/ad-campaigns/connection').then(unwrap),
  adSettings:      ()           => api.get('/ad-campaigns/settings').then(unwrap),
  saveAdSettings:  (b)          => api.put('/ad-campaigns/settings', b).then(unwrap),
  previewCampaign: (spec)       => api.post('/ad-campaigns/preview', spec).then(unwrap),
  createCampaign:  (spec)       => api.post('/ad-campaigns', spec).then(unwrap),
  launchCampaign:  (id)         => api.post(`/ad-campaigns/${id}/launch`).then(unwrap),
  pauseCampaign:   (id)         => api.post(`/ad-campaigns/${id}/pause`).then(unwrap),
  campaignBudget:  (id, rs)     => api.put(`/ad-campaigns/${id}/budget`, { daily_budget_rs: rs }).then(unwrap),
  syncAds:         ()           => api.post('/ad-campaigns/sync').then(unwrap),
  campaignHistory: (id)         => api.get(`/ad-campaigns/${id}/history`).then(unwrap),
  adRules:         ()           => api.get('/ad-campaigns/rules').then(unwrap),
  saveAdRule:      (b, id)      => (id ? api.put(`/ad-campaigns/rules/${id}`, b) : api.post('/ad-campaigns/rules', b)).then(unwrap),
  deleteAdRule:    (id)         => api.delete(`/ad-campaigns/rules/${id}`),
  adCopy:          (b)          => api.post('/ad-campaigns/ai-copy', b).then(unwrap),
  metaLeadForms:   (pageId)     => api.get(`/ad-campaigns/meta/lead-forms?page_id=${pageId}`).then(unwrap),
  metaGeo:         (q)          => api.get(`/ad-campaigns/meta/geo?q=${encodeURIComponent(q)}`).then(unwrap),
  googleGeo:       (q)          => api.get(`/ad-campaigns/google/geo?q=${encodeURIComponent(q)}`).then(unwrap),
  // billing documents
  billingProfile:   ()          => api.get('/billing-docs/profile').then(unwrap),
  saveBillingProfile: (b)       => api.put('/billing-docs/profile', b).then(unwrap),
  bookingDocs:      (id)        => api.get(`/billing-docs/bookings/${id}/documents`).then(unwrap),
  issueInvoice:     (id, b)     => api.post(`/billing-docs/bookings/${id}/invoice`, b).then(unwrap),
  creditNote:       (id, b)     => api.post(`/billing-docs/invoices/${id}/credit-note`, b).then(unwrap),
  issueReceipt:     (paymentId) => api.post(`/billing-docs/payments/${paymentId}/receipt`).then(unwrap),
  sendDocWhatsApp:  (kind, id)  => api.post('/billing-docs/send', { kind, id }).then(unwrap),
  setupDocTemplate: ()          => api.post('/billing-docs/whatsapp-template').then(unwrap),
  gstSummary:       (period)    => api.get(`/billing-docs/exports/summary?period=${period}`).then(unwrap),
  einvoiceSettings: ()          => api.get('/einvoice/settings').then(unwrap),
  saveEinvoice:     (b)         => api.put('/einvoice/settings', b).then(unwrap),
  testEinvoice:     ()          => api.post('/einvoice/test').then(unwrap),
  cancelEinvoice:   (id, reason, remark) => api.post(`/billing-docs/invoices/${id}/einvoice/cancel`, { reason, remark }).then(unwrap),
  gst3b:            (period)    => api.get(`/billing-docs/gst/3b?period=${period}`).then(unwrap),
  gstItc:           (period)    => api.get(`/billing-docs/gst/itc?period=${period}`).then(unwrap),
  saveGstItc:       (b)         => api.put('/billing-docs/gst/itc', b).then(unwrap),
  gstHsn:           (period)    => api.get(`/billing-docs/gst/hsn?period=${period}`).then(unwrap),
  gstFilings:       (fy)        => api.get(`/billing-docs/gst/filings?fy=${fy}`).then(unwrap),
  recordGstFiling:  (b)         => api.post('/billing-docs/gst/filings', b).then(unwrap),
  removeGstFiling:  (period, type) => api.delete(`/billing-docs/gst/filings?period=${period}&return=${type}`).then(unwrap),
  gstDownload:      (period, file) => downloadFile(`/billing-docs/exports/download?period=${period}&file=${file}`, file),
  tcsReport:        (fy, q)     => api.get(`/billing-docs/tcs/report?fy=${fy}&q=${q}`).then(unwrap),
  tcsDownload:      (fy, q)     => downloadFile(`/billing-docs/tcs/download?fy=${fy}&q=${q}`, 'TCS.csv'),
  tcsAddChallan:    (b)         => api.post('/billing-docs/tcs/challans', b).then(unwrap),
  tcsDeleteChallan: (id)        => api.delete(`/billing-docs/tcs/challans/${id}`).then(unwrap),
  setBookingPan:    (id, pan)   => api.put(`/billing-docs/bookings/${id}/pan`, { pan }).then(unwrap),
  payables:         (filter)    => api.get(`/payables?filter=${filter || 'all'}`).then(unwrap),
  payableService:   (id)        => api.get(`/payables/services/${id}`).then(unwrap),
  paySupplier:      (id, b)     => api.post(`/payables/services/${id}/pay`, b).then(unwrap),
  deleteSupplierPayment: (id)   => api.delete(`/payables/payments/${id}`).then(unwrap),
  checklist:        (bookingId) => api.get(`/checklists/bookings/${bookingId}`).then(unwrap),
  checklistGenerate: (bookingId) => api.post(`/checklists/bookings/${bookingId}`).then(unwrap),
  checklistSet:     (itemId, status, notes) => api.patch(`/checklists/items/${itemId}`, { status, notes }).then(unwrap),
  checklistOverview: (days)     => api.get(`/checklists/overview?days=${days || 60}`).then(unwrap),
  travelReport:     (from, to)  => api.get(`/travel-reports?from=${from}&to=${to}`).then(unwrap),
  departures:       (scope)     => api.get(`/departures?scope=${scope || 'upcoming'}`).then(unwrap),
  departure:        (id)        => api.get(`/departures/${id}`).then(unwrap),
  createDeparture:  (b)         => api.post('/departures', b).then(unwrap),
  updateDeparture:  (id, b)     => api.put(`/departures/${id}`, b).then(unwrap),
  departureStatus:  (id, st)    => api.post(`/departures/${id}/status`, { status: st }).then(unwrap),
  reserveSeats:     (id, b)     => api.post(`/departures/${id}/reserve`, b).then(unwrap),
  releaseSeats:     (holdId)    => api.delete(`/departures/holds/${holdId}`).then(unwrap),
  manifest:         (id)        => api.get(`/departures/${id}/manifest`).then(unwrap),
  manifestCsv:      (id)        => downloadFile(`/departures/${id}/manifest.csv`, 'manifest.csv'),
  leadSources:      ()          => api.get('/lead-sources').then(unwrap),
  saveLeadSource:   (b, id)     => (id ? api.put(`/lead-sources/${id}`, b) : api.post('/lead-sources', b)).then(unwrap),
  rotateLeadSource: (id)        => api.post(`/lead-sources/${id}/rotate`).then(unwrap),
  deleteLeadSource: (id)        => api.delete(`/lead-sources/${id}`).then(unwrap),
  leadSourceEvents: (id)        => api.get(`/lead-sources/${id}/events`).then(unwrap),
  openQuotePdf:     (itId)      => openPdf(`/billing-docs/itineraries/${itId}/pdf`),
  openInvoicePdf:   (id)        => openPdf(`/billing-docs/invoices/${id}/pdf`),
  // mobile push
  pushPrefs:       ()      => api.get('/mobile/push/preferences').then(unwrap),
  savePushPrefs:   (b)     => api.put('/mobile/push/preferences', b).then(unwrap),
  pushDevices:     ()      => api.get('/mobile/devices').then(unwrap),
  pushTest:        ()      => api.post('/mobile/push/test').then(unwrap),
  pushLog:         ()      => api.get('/mobile/push/log').then(unwrap),
  cancelBooking:(id, reason)  => api.post(`/bookings/${id}/cancel`, { reason }).then(unwrap),

  // public (no auth)
  portalView:   (token)       => fetch(`/api/v1/public/portal/${token}`).then(r => r.json()),
  portalPay:    (token, id)   => fetch(`/api/v1/public/portal/${token}/payments/${id}/link`, { method: 'POST' }).then(r => r.json()),
  portalUpload: (token, itemId, file) => { const f = new FormData(); f.append('file', file); return fetch(`/api/v1/public/portal/${token}/items/${itemId}/upload`, { method: 'POST', body: f }).then(r => r.json()) },
  portalLink:   (bookingId)   => api.post(`/portal/bookings/${bookingId}/link`).then(unwrap),
  portalRotate: (bookingId)   => api.post(`/portal/bookings/${bookingId}/rotate`).then(unwrap),
  portalUploads: (itemId)     => api.get(`/portal/items/${itemId}/uploads`).then(unwrap),
  portalOpenUpload: (id)      => openFile(`/portal/uploads/${id}/file`),
  portalReview: (id, decision, reason) => api.post(`/portal/uploads/${id}/review`, { decision, reason }).then(unwrap),
  publicQuote:  (token)       => fetch(`/api/v1/public/quotes/${token}`).then(r => r.json()),
  acceptQuote:  (token)       => fetch(`/api/v1/public/quotes/${token}/accept`, { method: 'POST' }).then(r => r.json()),
}

export const TRIP_STATUS = {
  enquiry:     { label: 'Enquiry',     bg: '#e8f3fc', color: '#074a8c' },
  quoted:      { label: 'Quoted',      bg: '#fef9c3', color: '#a16207' },
  negotiating: { label: 'Negotiating', bg: '#ffedd5', color: '#c2410c' },
  booked:      { label: 'Booked',      bg: '#dcfce7', color: '#15803d' },
  travelling:  { label: 'Travelling',  bg: '#e0f2fe', color: '#0369a1' },
  completed:   { label: 'Completed',   bg: '#f1f5f9', color: '#475569' },
  lost:        { label: 'Lost',        bg: '#fee2e2', color: '#b91c1c' },
  cancelled:   { label: 'Cancelled',   bg: '#fee2e2', color: '#b91c1c' },
}
